---

- name: restart filebeat
  supervisorctl:
    name: filebeat
    state: stopped
  ignore_errors: yes

- name: "Copy tar gz"
  become: yes
  copy:
    src: "{{ filebeat_download_path }}/{{ filebeat_tarball }}.tar.gz"
    dest: "/tmp/{{ filebeat_tarball }}.tar.gz"
    
- name: Extract the Filebeat tarball
  become: yes
  unarchive:
    src: "/tmp/{{ filebeat_tarball }}.tar.gz"
    dest: "/tmp/"
    copy: no

- name: Install Filebeat
  become: yes
  command: "cp -aT /tmp/{{ filebeat_tarball }} {{ filebeat_install_dir }}"
  notify: restart filebeat

- name: Install Filebeat as supervisord services
  become: yes
  template:
    src: "supervisor.ini.j2"
    dest: "{{ supervisord_conf_dir|default('/etc/supervisor/') }}/filebeat.ini"
    mode: "0644"
  notify: reread supervisord

- name: Install Filebeat Steve Configuration
  template:
    src: "steve.ini"
    dest: "/etc/steve/filebeat.ini"
    mode: "0644"
  become: yes
  when: has_giko_steve == True
  




