---

- include: tasks/set-role-variables.yml


- stat:
    path: "/etc/steve"
  register: steve_st

- set_fact:
    has_giko_steve: true
  when: steve_st.stat.exists == true and steve_st.stat.isdir == true

- set_fact:
    has_giko_steve: false
  when: steve_st.stat.exists == false or steve_st.stat.isdir == false

- name: Install Filebeat
  include: install.yml
  tags:
    - build

- name: Configure Filebeat
  include: configure.yml
  tags:
    - configure

# - name: Ensure Filebeat is started and enabled at boot.
#   service:
#     name: filebeat
#     state: started
#     enabled: yes

# - name: Restart filebeat
#   supervisorctl:
#     name: filebeat
#     state: present
#   when: has_giko_steve == false

# - name: Restart filebeat
#   shell: "steve -k restart -s filebeat"
#   become: True
#   tags: ["setup"]
#   when: has_giko_steve == true


- name: Remove tmp files
  become: yes
  file:
    path: "/tmp/{{ filebeat_tarball }}"
    state: absent
    