---



#  service: name=filebeat state=restarted
#  when: ansible_service_mgr is defined and ansible_service_mgr == 'systemd'

- name: reread supervisord
  command: supervisorctl reread && supervisorctl update filebeat


- name: restart filebeat
  supervisorctl:
    name: filebeat
    state: restarted
  become: yes
